// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppCEMV
{
    [Table("ANIMAL")]
    public partial class Animal
    {
        [Key]
        [Column("ANIMAL_ID")]
        public int AnimalId { get; set; }
        [Required]
        [Column("NOME")]
        [StringLength(100)]
        public string Nome { get; set; }
        [Column("TUTOR_ID")]
        public int? TutorId { get; set; }
        [Column("ESPECIE_ID")]
        public short? EspecieId { get; set; }
        [Column("RACA_ID")]
        public short? RacaId { get; set; }
        [Column("PELAGEM_ID")]
        public byte? PelagemId { get; set; }
        [Column("COR_ID")]
        public short? CorId { get; set; }
        [Column("SEXO_ID")]
        public byte? SexoId { get; set; }
        [Column("COMOCHEGOU_ID")]
        public short? ComochegouId { get; set; }
        [Column("PORTE_ID")]
        public byte? PorteId { get; set; }
        [Column("DATANASCIMENTO", TypeName = "date")]
        public DateTime? Datanascimento { get; set; }
        [Column("INDICADORESTIMADA")]
        public bool Indicadorestimada { get; set; }
        [Column("PEDIGREE")]
        [StringLength(50)]
        public string Pedigree { get; set; }
        [Column("CHIP")]
        [StringLength(50)]
        public string Chip { get; set; }
        [Column("CCI")]
        [StringLength(50)]
        public string Cci { get; set; }
        [Column("INDICADORMORTO")]
        public bool Indicadormorto { get; set; }
        [Column("INDICADORCASTRADO")]
        public bool Indicadorcastrado { get; set; }
        [Column("OBSERVACOES")]
        public string Observacoes { get; set; }
        [Column("FOTO")]
        [StringLength(255)]
        public string Foto { get; set; }
        [Column("DATACADASTRO", TypeName = "datetime")]
        public DateTime? Datacadastro { get; set; }
        [Column("USUARIOCADASTRO_ID")]
        public short? UsuariocadastroId { get; set; }

        [ForeignKey(nameof(ComochegouId))]
        [InverseProperty("Animal")]
        public virtual Comochegou Comochegou { get; set; }
        [ForeignKey(nameof(CorId))]
        [InverseProperty("Animal")]
        public virtual Cor Cor { get; set; }
        [ForeignKey(nameof(EspecieId))]
        [InverseProperty("Animal")]
        public virtual Especie Especie { get; set; }
        [ForeignKey(nameof(RacaId))]
        [InverseProperty("Animal")]
        public virtual Raca Raca { get; set; }
        [ForeignKey(nameof(TutorId))]
        [InverseProperty("Animal")]
        public virtual Tutor Tutor { get; set; }
        [ForeignKey(nameof(UsuariocadastroId))]
        [InverseProperty(nameof(Usuario.Animal))]
        public virtual Usuario Usuariocadastro { get; set; }
    }
}