// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppCEMV
{
    [Table("APRESENTACAO")]
    public partial class Apresentacao
    {
        public Apresentacao()
        {
            Produto = new HashSet<Produto>();
        }

        [Key]
        [Column("APRESENTACAO_ID")]
        public short ApresentacaoId { get; set; }
        [Required]
        [Column("DESCRICAO")]
        [StringLength(100)]
        public string Descricao { get; set; }

        [InverseProperty("Apresentacao")]
        public virtual ICollection<Produto> Produto { get; set; }
    }
}