// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppCEMV
{
    [Table("CLINICA")]
    public partial class Clinica
    {
        public Clinica()
        {
            Clinicatelefone = new HashSet<Clinicatelefone>();
            Tutor = new HashSet<Tutor>();
            Usuario = new HashSet<Usuario>();
        }

        [Key]
        [Column("CLINICA_ID")]
        public short ClinicaId { get; set; }
        [Required]
        [Column("RAZAOSOCIAL")]
        [StringLength(150)]
        public string Razaosocial { get; set; }
        [Required]
        [Column("CNPJ")]
        [StringLength(15)]
        public string Cnpj { get; set; }
        [Required]
        [Column("NOMEFANTASIA")]
        [StringLength(150)]
        public string Nomefantasia { get; set; }
        [Column("INSCRICAOESTADUAL")]
        [StringLength(30)]
        public string Inscricaoestadual { get; set; }
        [Column("INSCRICAOMUNICIPAL")]
        [StringLength(30)]
        public string Inscricaomunicipal { get; set; }
        [Column("TIPOLOGRADOURO_ID")]
        public byte TipologradouroId { get; set; }
        [Required]
        [Column("LOGRADOURO")]
        [StringLength(150)]
        public string Logradouro { get; set; }
        [Required]
        [Column("NUMERO")]
        [StringLength(10)]
        public string Numero { get; set; }
        [Column("COMPLEMENTO")]
        [StringLength(50)]
        public string Complemento { get; set; }
        [Column("BAIRRO_ID")]
        public int? BairroId { get; set; }
        [Column("CIDADE_ID")]
        public short? CidadeId { get; set; }
        [Required]
        [Column("CEP")]
        [StringLength(10)]
        public string Cep { get; set; }
        [Column("ESTADO_ID")]
        public byte EstadoId { get; set; }
        [Required]
        [Column("EMAIL")]
        [StringLength(50)]
        public string Email { get; set; }
        [Column("DATACADASTRO", TypeName = "datetime")]
        public DateTime? Datacadastro { get; set; }
        [Required]
        [Column("INDICADORATIVO")]
        public bool? Indicadorativo { get; set; }
        [Column("USUARIOCADASTRO_ID")]
        public short UsuariocadastroId { get; set; }
        [Column("LOGOMARCA")]
        [StringLength(150)]
        public string Logomarca { get; set; }
        [Column("INDICADORMATRIZ")]
        public bool? Indicadormatriz { get; set; }

        [ForeignKey(nameof(BairroId))]
        [InverseProperty(nameof(TabBairro.Clinica))]
        public virtual TabBairro Bairro { get; set; }
        [ForeignKey(nameof(CidadeId))]
        [InverseProperty(nameof(TabCidade.Clinica))]
        public virtual TabCidade Cidade { get; set; }
        [ForeignKey(nameof(EstadoId))]
        [InverseProperty(nameof(TabEstado.Clinica))]
        public virtual TabEstado Estado { get; set; }
        [InverseProperty("Clinica")]
        public virtual ICollection<Clinicatelefone> Clinicatelefone { get; set; }
        [InverseProperty("Clinica")]
        public virtual ICollection<Tutor> Tutor { get; set; }
        [InverseProperty("Clinica")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}