// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppCEMV
{
    [Table("CONCENTRACAO")]
    public partial class Concentracao
    {
        public Concentracao()
        {
            Produto = new HashSet<Produto>();
        }

        [Key]
        [Column("CONCENTRACAO_ID")]
        public short ConcentracaoId { get; set; }
        [Required]
        [Column("DESCRICAO")]
        [StringLength(100)]
        public string Descricao { get; set; }

        [InverseProperty("Concentracao")]
        public virtual ICollection<Produto> Produto { get; set; }
    }
}