// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppCEMV
{
    [Table("ESPECIALIDADE")]
    public partial class Especialidade
    {
        public Especialidade()
        {
            Especialidadeusuario = new HashSet<Especialidadeusuario>();
        }

        [Key]
        [Column("ESPECIALIDADE_ID")]
        public short EspecialidadeId { get; set; }
        [Column("PROFISSAO_ID")]
        public short? ProfissaoId { get; set; }
        [Required]
        [Column("DESCRICAO")]
        [StringLength(100)]
        public string Descricao { get; set; }

        [ForeignKey(nameof(ProfissaoId))]
        [InverseProperty("Especialidade")]
        public virtual Profissao Profissao { get; set; }
        [InverseProperty("Especialidade")]
        public virtual ICollection<Especialidadeusuario> Especialidadeusuario { get; set; }
    }
}