// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppCEMV
{
    [Table("ESPECIE")]
    public partial class Especie
    {
        public Especie()
        {
            Animal = new HashSet<Animal>();
            Raca = new HashSet<Raca>();
        }

        [Key]
        [Column("ESPECIE_ID")]
        public short EspecieId { get; set; }
        [Required]
        [Column("DESCRICAO")]
        [StringLength(20)]
        public string Descricao { get; set; }
        [Column("TIPOESPECIE_ID")]
        public byte TipoespecieId { get; set; }

        [InverseProperty("Especie")]
        public virtual ICollection<Animal> Animal { get; set; }
        [InverseProperty("Especie")]
        public virtual ICollection<Raca> Raca { get; set; }
    }
}