// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppCEMV
{
    [Table("ESPECIALIDADEUSUARIO")]
    public partial class Especialidadeusuario
    {
        [Key]
        [Column("ESPECIALIDADEUSUARIO_ID")]
        public long EspecialidadeusuarioId { get; set; }
        [Column("USUARIO_ID")]
        public short UsuarioId { get; set; }
        [Column("ESPECIALIDADE_ID")]
        public short EspecialidadeId { get; set; }

        [ForeignKey(nameof(EspecialidadeId))]
        [InverseProperty("Especialidadeusuario")]
        public virtual Especialidade Especialidade { get; set; }
        [ForeignKey(nameof(UsuarioId))]
        [InverseProperty("Especialidadeusuario")]
        public virtual Usuario Usuario { get; set; }
    }
}