// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppCEMV
{
    [Table("ESTOQUE")]
    public partial class Estoque
    {
        public Estoque()
        {
            Produto = new HashSet<Produto>();
        }

        [Key]
        [Column("ESTOQUE_ID")]
        public int EstoqueId { get; set; }
        [Column("PRODUTO_ID")]
        public int ProdutoId { get; set; }
        [Column("ESTOQUEMINIMO")]
        public short Estoqueminimo { get; set; }
        [Column("ESTOQUEIDEAL")]
        public short Estoqueideal { get; set; }
        [Column("ESTOQUEMAXIMO")]
        public short Estoquemaximo { get; set; }
        [Column("ESTOQUEATUAL")]
        public short Estoqueatual { get; set; }

        [InverseProperty("Estoque")]
        public virtual ICollection<Produto> Produto { get; set; }
    }
}