// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppCEMV
{
    [Table("FABRICANTE")]
    public partial class Fabricante
    {
        public Fabricante()
        {
            Produto = new HashSet<Produto>();
        }

        [Key]
        [Column("FABRICANTE_ID")]
        public short FabricanteId { get; set; }
        [Required]
        [Column("NOME")]
        [StringLength(255)]
        public string Nome { get; set; }

        [InverseProperty("Fabricante")]
        public virtual ICollection<Produto> Produto { get; set; }
    }
}