// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppCEMV
{
    [Table("FUNCIONALIDADEUSUARIO")]
    public partial class Funcionalidadeusuario
    {
        [Key]
        [Column("FUNCIONALIDADEUSUARIO_ID")]
        public long FuncionalidadeusuarioId { get; set; }
        [Column("FUNCIONALIDADE_ID")]
        public int? FuncionalidadeId { get; set; }
        [Column("USUARIO_ID")]
        public short? UsuarioId { get; set; }
        [Column("INDICADORCONSULTA")]
        public bool? Indicadorconsulta { get; set; }
        [Column("INDICADORALTERACAO")]
        public bool? Indicadoralteracao { get; set; }

        [ForeignKey(nameof(FuncionalidadeId))]
        [InverseProperty("Funcionalidadeusuario")]
        public virtual Funcionalidade Funcionalidade { get; set; }
        [ForeignKey(nameof(UsuarioId))]
        [InverseProperty("Funcionalidadeusuario")]
        public virtual Usuario Usuario { get; set; }
    }
}