// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppCEMV
{
    [Table("FUNCIONALIDADEPERFIL")]
    public partial class Funcionalidadeperfil
    {
        [Key]
        [Column("FUNCIONALIDADEPERFIL_ID")]
        public long FuncionalidadeperfilId { get; set; }
        [Column("FUNCIONALIDADE_ID")]
        public int FuncionalidadeId { get; set; }
        [Column("PERFIL_ID")]
        public short PerfilId { get; set; }
        [Column("INDICADORCONSULTA")]
        public bool? Indicadorconsulta { get; set; }
        [Column("INDICADORALTERACAO")]
        public bool? Indicadoralteracao { get; set; }

        [ForeignKey(nameof(FuncionalidadeId))]
        [InverseProperty("Funcionalidadeperfil")]
        public virtual Funcionalidade Funcionalidade { get; set; }
        [ForeignKey(nameof(PerfilId))]
        [InverseProperty("Funcionalidadeperfil")]
        public virtual Perfil Perfil { get; set; }
    }
}