// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppCEMV
{
    [Table("PERFIL")]
    public partial class Perfil
    {
        public Perfil()
        {
            Funcionalidadeperfil = new HashSet<Funcionalidadeperfil>();
            Usuario = new HashSet<Usuario>();
        }

        [Key]
        [Column("PERFIL_ID")]
        public short PerfilId { get; set; }
        [Required]
        [Column("NOME")]
        [StringLength(100)]
        public string Nome { get; set; }
        [Column("INDICADORPADRAO")]
        public bool Indicadorpadrao { get; set; }

        [InverseProperty("Perfil")]
        public virtual ICollection<Funcionalidadeperfil> Funcionalidadeperfil { get; set; }
        [InverseProperty("Perfil")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}