// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppCEMV
{
    [Table("PRINCIPIO")]
    public partial class Principio
    {
        public Principio()
        {
            Produto = new HashSet<Produto>();
        }

        [Key]
        [Column("PRINCIPIO_ID")]
        public int PrincipioId { get; set; }
        [Required]
        [Column("DESCRICAO")]
        [StringLength(100)]
        public string Descricao { get; set; }

        [InverseProperty("Principio")]
        public virtual ICollection<Produto> Produto { get; set; }
    }
}