// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppCEMV
{
    [Table("PRODUTO")]
    public partial class Produto
    {
        public Produto()
        {
            Produtopreco = new HashSet<Produtopreco>();
        }

        [Key]
        [Column("PRODUTO_ID")]
        public int ProdutoId { get; set; }
        [Column("FABRICANTE_ID")]
        public short? FabricanteId { get; set; }
        [Column("APRESENTACAO_ID")]
        public short? ApresentacaoId { get; set; }
        [Column("CONCENTRACAO_ID")]
        public short? ConcentracaoId { get; set; }
        [Column("VOLUME_ID")]
        public short? VolumeId { get; set; }
        [Required]
        [Column("NOME")]
        [StringLength(255)]
        public string Nome { get; set; }
        [Column("TIPOPRODUTO_ID")]
        public short TipoprodutoId { get; set; }
        [Column("PRINCIPIO_ID")]
        public int? PrincipioId { get; set; }
        [Column("ESTOQUE_ID")]
        public int? EstoqueId { get; set; }
        [Column("DATACADASTRO", TypeName = "datetime")]
        public DateTime Datacadastro { get; set; }
        [Column("ESTOQUEMINIMO")]
        public short Estoqueminimo { get; set; }
        [Column("ESTOQUEIDEAL")]
        public short Estoqueideal { get; set; }
        [Column("ESTOQUEMAXIMO")]
        public short Estoquemaximo { get; set; }
        [Column("CODIGOBARRAS")]
        [StringLength(20)]
        public string Codigobarras { get; set; }
        [Column("FOTO")]
        [StringLength(255)]
        public string Foto { get; set; }
        [Column("INDICADORATIVO")]
        public bool Indicadorativo { get; set; }
        [Column("UNIDADEVENDA_ID")]
        public short UnidadevendaId { get; set; }

        [ForeignKey(nameof(ApresentacaoId))]
        [InverseProperty("Produto")]
        public virtual Apresentacao Apresentacao { get; set; }
        [ForeignKey(nameof(ConcentracaoId))]
        [InverseProperty("Produto")]
        public virtual Concentracao Concentracao { get; set; }
        [ForeignKey(nameof(EstoqueId))]
        [InverseProperty("Produto")]
        public virtual Estoque Estoque { get; set; }
        [ForeignKey(nameof(FabricanteId))]
        [InverseProperty("Produto")]
        public virtual Fabricante Fabricante { get; set; }
        [ForeignKey(nameof(PrincipioId))]
        [InverseProperty("Produto")]
        public virtual Principio Principio { get; set; }
        [ForeignKey(nameof(TipoprodutoId))]
        [InverseProperty("Produto")]
        public virtual Tipoproduto Tipoproduto { get; set; }
        [ForeignKey(nameof(VolumeId))]
        [InverseProperty("Produto")]
        public virtual Volume Volume { get; set; }
        [InverseProperty("Produto")]
        public virtual ICollection<Produtopreco> Produtopreco { get; set; }
    }
}