// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppCEMV
{
    [Table("PRODUTOPRECO")]
    public partial class Produtopreco
    {
        [Key]
        [Column("PRODUTOPRECO_ID")]
        public long ProdutoprecoId { get; set; }
        [Column("PRODUTO_ID")]
        public int ProdutoId { get; set; }
        [Column("PRECOVENDA", TypeName = "decimal(11, 3)")]
        public decimal Precovenda { get; set; }
        [Column("DATAPRECOINICIO", TypeName = "datetime")]
        public DateTime Dataprecoinicio { get; set; }
        [Column("DATAPRECOFIM", TypeName = "datetime")]
        public DateTime? Dataprecofim { get; set; }

        [ForeignKey(nameof(ProdutoId))]
        [InverseProperty("Produtopreco")]
        public virtual Produto Produto { get; set; }
    }
}