// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppCEMV
{
    [Table("PROFISSAO")]
    public partial class Profissao
    {
        public Profissao()
        {
            Especialidade = new HashSet<Especialidade>();
            Tutor = new HashSet<Tutor>();
            Usuario = new HashSet<Usuario>();
        }

        [Key]
        [Column("PROFISSAO_ID")]
        public short ProfissaoId { get; set; }
        [Required]
        [Column("DESCRICAO")]
        [StringLength(100)]
        public string Descricao { get; set; }

        [InverseProperty("Profissao")]
        public virtual ICollection<Especialidade> Especialidade { get; set; }
        [InverseProperty("ProfissaoNavigation")]
        public virtual ICollection<Tutor> Tutor { get; set; }
        [InverseProperty("Profissao")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}