// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppCEMV
{
    [Table("TAB_ESTADO")]
    public partial class TabEstado
    {
        public TabEstado()
        {
            Clinica = new HashSet<Clinica>();
            TabCidade = new HashSet<TabCidade>();
            Tutor = new HashSet<Tutor>();
            UsuarioEstado = new HashSet<Usuario>();
            UsuarioEstadocrmv = new HashSet<Usuario>();
        }

        [Key]
        [Column("ESTADO_ID")]
        public byte EstadoId { get; set; }
        [Required]
        [Column("SIGLA")]
        [StringLength(5)]
        public string Sigla { get; set; }
        [Required]
        [Column("NOME")]
        [StringLength(50)]
        public string Nome { get; set; }

        [InverseProperty("Estado")]
        public virtual ICollection<Clinica> Clinica { get; set; }
        [InverseProperty("Estado")]
        public virtual ICollection<TabCidade> TabCidade { get; set; }
        [InverseProperty("Estado")]
        public virtual ICollection<Tutor> Tutor { get; set; }
        [InverseProperty(nameof(Usuario.Estado))]
        public virtual ICollection<Usuario> UsuarioEstado { get; set; }
        [InverseProperty(nameof(Usuario.Estadocrmv))]
        public virtual ICollection<Usuario> UsuarioEstadocrmv { get; set; }
    }
}