// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppCEMV
{
    [Table("USUARIO")]
    public partial class Usuario
    {
        public Usuario()
        {
            Animal = new HashSet<Animal>();
            Especialidadeusuario = new HashSet<Especialidadeusuario>();
            Funcionalidadeusuario = new HashSet<Funcionalidadeusuario>();
            TutorUsuariocadastro = new HashSet<Tutor>();
            TutorUsuariopreferencia = new HashSet<Tutor>();
            Usuariotelefone = new HashSet<Usuariotelefone>();
        }

        [Key]
        [Column("USUARIO_ID")]
        public short UsuarioId { get; set; }
        [Required]
        [Column("NOME")]
        [StringLength(150)]
        public string Nome { get; set; }
        [Required]
        [Column("CPF")]
        [StringLength(11)]
        public string Cpf { get; set; }
        [Column("RG")]
        [StringLength(20)]
        public string Rg { get; set; }
        [Column("TIPOUSUARIO_ID")]
        public byte? TipousuarioId { get; set; }
        [Column("DATANASCIMENTO", TypeName = "date")]
        public DateTime? Datanascimento { get; set; }
        [Column("DATACADASTRO", TypeName = "datetime")]
        public DateTime? Datacadastro { get; set; }
        [Column("TIPOLOGRADOURO_ID")]
        public byte? TipologradouroId { get; set; }
        [Column("LOGRADOURO")]
        [StringLength(150)]
        public string Logradouro { get; set; }
        [Column("NUMERO")]
        [StringLength(10)]
        public string Numero { get; set; }
        [Column("COMPLEMENTO")]
        [StringLength(50)]
        public string Complemento { get; set; }
        [Column("BAIRRO_ID")]
        public int? BairroId { get; set; }
        [Column("CIDADE_ID")]
        public short? CidadeId { get; set; }
        [Column("CEP")]
        [StringLength(10)]
        public string Cep { get; set; }
        [Column("ESTADO_ID")]
        public byte? EstadoId { get; set; }
        [Column("EMAIL")]
        [StringLength(50)]
        public string Email { get; set; }
        [Column("INDICADORATIVO")]
        public bool? Indicadorativo { get; set; }
        [Column("DATADESATIVACAO", TypeName = "date")]
        public DateTime? Datadesativacao { get; set; }
        [Column("FOTO")]
        [StringLength(255)]
        public string Foto { get; set; }
        [Column("CRMV")]
        [StringLength(20)]
        public string Crmv { get; set; }
        [Column("ESTADOCRMV_ID")]
        public byte? EstadocrmvId { get; set; }
        [Column("CLINICA_ID")]
        public short? ClinicaId { get; set; }
        [Column("PERFIL_ID")]
        public short? PerfilId { get; set; }
        [Column("PROFISSAO_ID")]
        public short? ProfissaoId { get; set; }

        [ForeignKey(nameof(BairroId))]
        [InverseProperty(nameof(TabBairro.Usuario))]
        public virtual TabBairro Bairro { get; set; }
        [ForeignKey(nameof(CidadeId))]
        [InverseProperty(nameof(TabCidade.Usuario))]
        public virtual TabCidade Cidade { get; set; }
        [ForeignKey(nameof(ClinicaId))]
        [InverseProperty("Usuario")]
        public virtual Clinica Clinica { get; set; }
        [ForeignKey(nameof(EstadoId))]
        [InverseProperty(nameof(TabEstado.UsuarioEstado))]
        public virtual TabEstado Estado { get; set; }
        [ForeignKey(nameof(EstadocrmvId))]
        [InverseProperty(nameof(TabEstado.UsuarioEstadocrmv))]
        public virtual TabEstado Estadocrmv { get; set; }
        [ForeignKey(nameof(PerfilId))]
        [InverseProperty("Usuario")]
        public virtual Perfil Perfil { get; set; }
        [ForeignKey(nameof(ProfissaoId))]
        [InverseProperty("Usuario")]
        public virtual Profissao Profissao { get; set; }
        [InverseProperty("Usuariocadastro")]
        public virtual ICollection<Animal> Animal { get; set; }
        [InverseProperty("Usuario")]
        public virtual ICollection<Especialidadeusuario> Especialidadeusuario { get; set; }
        [InverseProperty("Usuario")]
        public virtual ICollection<Funcionalidadeusuario> Funcionalidadeusuario { get; set; }
        [InverseProperty(nameof(Tutor.Usuariocadastro))]
        public virtual ICollection<Tutor> TutorUsuariocadastro { get; set; }
        [InverseProperty(nameof(Tutor.Usuariopreferencia))]
        public virtual ICollection<Tutor> TutorUsuariopreferencia { get; set; }
        [InverseProperty("Usuario")]
        public virtual ICollection<Usuariotelefone> Usuariotelefone { get; set; }
    }
}