// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppCEMV
{
    [Table("VOLUME")]
    public partial class Volume
    {
        public Volume()
        {
            Produto = new HashSet<Produto>();
        }

        [Key]
        [Column("VOLUME_ID")]
        public short VolumeId { get; set; }
        [Required]
        [Column("DESCRICAO")]
        [StringLength(100)]
        public string Descricao { get; set; }

        [InverseProperty("Volume")]
        public virtual ICollection<Produto> Produto { get; set; }
    }
}